/**
 * Attaches a correlation id and start time to every request.
 *
 * The id is echoed back in the `X-Request-Id` response header and included in
 * every log line for that request. When a user reports "it failed at 14:05",
 * the id from their browser's network tab locates the exact server-side trace.
 *
 * An inbound `X-Request-Id` is honoured so a value generated by the frontend
 * (or an upstream gateway) survives the whole chain.
 */

import { randomUUID } from 'node:crypto'

/** Rejects absurd or malformed inbound ids so a header cannot poison the logs. */
const ID_PATTERN = /^[\w.:-]{1,128}$/

/** @type {import('express').RequestHandler} */
export function requestContext(req, res, next) {
  const inbound = req.get('X-Request-Id')
  req.id = inbound && ID_PATTERN.test(inbound) ? inbound : randomUUID()
  req.startTime = process.hrtime.bigint()

  res.setHeader('X-Request-Id', req.id)
  next()
}

export default requestContext
